name: Create and publish a Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: caddy-aneekl

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - files: ./Dockerfile.cf
            tags: cf
          - files: ./Dockerfile.docker
            tags: docker
          - files: ./Dockerfile.dockercf
            tags: dockercf

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.files }}
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ matrix.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Build and push Docker images
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./Dockerfile.docker
      #     platforms: linux/amd64, linux/arm64, linux/arm/7
      #     push: true
      #     tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:docker
      #     labels: ${{ steps.meta.outputs.labels }}

      # - name: Build and push Docker images
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./Dockerfile.docker
      #     platforms: linux/amd64, linux/arm64, linux/arm/7
      #     push: true
      #     tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:dockercf
      #     labels: ${{ steps.meta.outputs.labels }}
